name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 3
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build:ci" --agent-count=3
      install-commands: | 
        pnpm install --no-frozen-lockfile
      parallel-commands-on-agents: |
        pnpm exec lerna run build:ci --concurrent 3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
